//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:2.0.50727.3053
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PocketLadioDeux {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class MessagesResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal MessagesResource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PocketLadioDeux.MessagesResource", typeof(MessagesResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   The Headline &quot;{0}&quot; fetching was canceled. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CancelFetchChannels {
            get {
                return ResourceManager.GetString("CancelFetchChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t allocate memory. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanNotAllocateMemory {
            get {
                return ResourceManager.GetString("CanNotAllocateMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t download the playlist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanNotDownloadPlaylist {
            get {
                return ResourceManager.GetString("CanNotDownloadPlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t fetch the headline &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CanNotFetchChannels {
            get {
                return ResourceManager.GetString("CanNotFetchChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The error occurred while fetching headline &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptFetchChannels {
            get {
                return ResourceManager.GetString("ExceptFetchChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The IO error occurred while fetching headline &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptIOErrorFetchChannels {
            get {
                return ResourceManager.GetString("ExceptIOErrorFetchChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Can&apos;t parse xml of the headline &quot;{0}&quot;. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ExceptXmlErrorFetchChannels {
            get {
                return ResourceManager.GetString("ExceptXmlErrorFetchChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The headline &quot;{0}&quot; URL is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HeadlineUrlInvalid {
            get {
                return ResourceManager.GetString("HeadlineUrlInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Infomation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Infomation {
            get {
                return ResourceManager.GetString("Infomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The media player is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MediaPlayerNotFound {
            get {
                return ResourceManager.GetString("MediaPlayerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play URL is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayUrlIsEmpty {
            get {
                return ResourceManager.GetString("PlayUrlIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please set the media player and the web browser file path. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleaseSettingPath {
            get {
                return ResourceManager.GetString("PleaseSettingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel is not selected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SelectedChannelIsEmpty {
            get {
                return ResourceManager.GetString("SelectedChannelIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The web browser is not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebBrowserNotFound {
            get {
                return ResourceManager.GetString("WebBrowserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Web site URL is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WebSiteUrlIsEmpty {
            get {
                return ResourceManager.GetString("WebSiteUrlIsEmpty", resourceCulture);
            }
        }
    }
}
